# Generated by Django 3.0.2 on 2020-01-12 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbview', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashflow',
            name='company_from',
            field=models.CharField(default='from', max_length=63),
        ),
        migrations.AddField(
            model_name='cashflow',
            name='company_to',
            field=models.CharField(default='to', max_length=63),
        ),
    ]
