# Generated by Django 3.0.2 on 2020-01-12 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbview', '0002_auto_20200112_0352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashflow',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
