# Generated by Django 3.0.2 on 2020-01-12 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbview', '0003_auto_20200112_0356'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempWeek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_from', models.CharField(default='from', max_length=63)),
                ('company_to', models.CharField(default='to', max_length=63)),
                ('sum', models.FloatField()),
            ],
            options={
                'db_table': 'temp_week',
                'managed': False,
            },
        ),
    ]
